# WINDOW
APP_TITLE = "Penerjemah Bahasa Isyarat BISINDO"
APP_WIDTH = 1200
APP_HEIGHT = 700

# DATASET
DATASET_PATH = "data/dataset"
PROCESSED_DATASET_PATH = "data/processed"

# MODEL
MODEL_PATH = "models/gesture_model.pkl"

# OUTPUT
OUTPUT_AUDIO_PATH = "output/audio"

# ASSETS
GESTURE_IMAGE_PATH = "assets/gesture_images"

# CAMERA
CAMERA_INDEX = 0
CAMERA_WIDTH = 1280
CAMERA_HEIGHT = 720
CAMERA_FPS = 30

# DATA COLLECTION
COUNTDOWN_TIME = 5
DEFAULT_IMAGE_COUNT = 100

# TRAINING
TEST_SIZE = 0.2
RANDOM_STATE = 42

# MEDIAPIPE
MAX_HANDS = 2
MIN_DETECTION_CONFIDENCE = 0.7
MIN_TRACKING_CONFIDENCE = 0.7

# PREDICTION
CONFIDENCE_THRESHOLD = 0.90

# KBBI
DICTIONARY_PATH = "data/kbbi_v6.1.0_full.csv"